# Copyright (C) 2025 Jasper Boom
# All Rights Reserved.
#
# Unauthorized copying, distribution, modification, or use of this file,
# in whole or in part, is strictly prohibited without prior written consent
# from the copyright owner.
#
# For licensing inquiries, contact: info@jboom.org

theme: jekyll-theme-cayman